--------------------------------------------------------------------------------
-- JDBC02 복습할 때 만들었다가 삭제함(22.04.20)
--------------------------------------------------------------------------------
CREATE TABLE MEMBER
( SID   NUMBER
, NAME  VARCHAR2(30)    NOT NULL
, TEL   VARCHAR2(40)
, CONSTRAINT SID_PK PRIMARY KEY(SID)
);
--==>> Table MEMBER이(가) 생성되었습니다.
DROP TABLE MEMBER;
DROP SEQUENCE SEQ_MEMBER;
-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER
NOCACHE;


--INSERT
INSERT INTO MEMBER(SID, NAME, TEL) VALUES(SEQ_MEMBER.NEXTVAL, '김정용', '010-1111-1111')
;

--전체조회
SELECT SID, NAME, TEL FROM MEMBER ORDER BY SID
;

--인원수
SELECT COUNT(*) AS COUNT FROM MEMBER
;

--UPDATE
UPDATE MEMBER SET NAME='김정용', TEL='010-1110-1110' WHERE SID=1
;

--DELETE
DELETE MEMBER WHERE SID=1
;

COMMIT;
ROLLBACK;

SELECT *
FROM MEMBER;

--------------------------------------------------------------------------------
-- JDBC05 Member (기존 TBL_EMP로 그대로 작업해도 될 듯) (22.04.20)
--------------------------------------------------------------------------------
SELECT * FROM TBL_EMP;
/*
TBL_EMP (EMP_ID, EMP_NAME, SSN, IBSADATE
       , CITY_ID, TEL, BUSEO_ID, JIKWI_ID, BASICPAY, SUDANG) + PAY
TBL_CITY (CITY_ID, CITY_NAME)
TBL_BUSEO (BUSEO_ID, BUSEO_NAME)
TBL_JIKWI (JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
*/

--1.직원정보입력
--CITY, BUSEO, JIKWI 각각 이름으로 ID조회
SELECT CITY_ID FROM TBL_CITY WHERE CITY_NAME='서울';
SELECT BUSEO_ID FROM TBL_BUSEO WHERE BUSEO_NAME='개발부';
SELECT JIKWI_ID FROM TBL_JIKWI WHERE JIKWI_NAME='부장';

INSERT INTO TBL_EMP(EMP_ID, EMP_NAME, SSN, IBSADATE, CITY_ID, TEL, BUSEO_ID, JIKWI_ID, BASICPAY, SUDANG)
VALUES(EMPSEQ.NEXTVAL, '김정용', '960608-2234567', TO_DATE(SYSDATE, 'YYYY-MM-DD')
     , (SELECT CITY_ID FROM TBL_CITY WHERE CITY_NAME='서울')
     , '010-1234-1234'
     , (SELECT BUSEO_ID FROM TBL_BUSEO WHERE BUSEO_NAME='개발부')
     , (SELECT JIKWI_ID FROM TBL_JIKWI WHERE JIKWI_NAME='부장')
     , 5000000, 1000000);

-- VIEW 생성 (기존 EMPVIEW 사용하고, 코드만 짜보자)
SELECT * FROM EMPVIEW;

SELECT E.EMP_ID, E.EMP_NAME, E.SSN, E.IBSADATE, C.CITY_NAME, E.TEL
     , B.BUSEO_NAME, J.JIKWI_NAME, E.BASICPAY, E.SUDANG
     , (NVL(BASICPAY, 0) + NVL(SUDANG, 0)) AS PAY
FROM TBL_EMP E JOIN TBL_CITY C ON E.CITY_ID = C.CITY_ID
               JOIN TBL_BUSEO B ON E.BUSEO_ID = B.BUSEO_ID
               JOIN TBL_JIKWI J ON E.JIKWI_ID = J.JIKWI_ID;

--전체 인원 수 출력
SELECT COUNT(*) AS COUNT FROM EMPVIEW;

--검색 인원 수 출력(사번/이름/부서/직위)
SELECT COUNT(*) AS COUNT FROM EMPVIEW WHERE EMP_ID=1066;
SELECT COUNT(*) AS COUNT FROM EMPVIEW WHERE EMP_NAME='김정용';
SELECT COUNT(*) AS COUNT FROM EMPVIEW WHERE BUSEO_NAME='개발부';
SELECT COUNT(*) AS COUNT FROM EMPVIEW WHERE JIKWI_NAME='사원';

--2.직원전체출력(사번/이름/부서/직위/급여내림차순 정렬)
SELECT EMP_ID, EMP_NAME, SSN, IBSADATE, CITY_NAME, TEL, BUSEO_NAME, JIKWI_NAME, BASICPAY, SUDANG, PAY
FROM EMPVIEW
ORDER BY EMP_ID;
--ORDER BY EMP_NAME;
--ORDER BY BUSEO_NAME;
--ORDER BY JIKWI_NAME;
--ORDER BY PAY DESC;

--3.직원검색출력(사번/이름/부서/직위)
SELECT EMP_ID, EMP_NAME, SSN, IBSADATE, CITY_NAME, TEL, BUSEO_NAME, JIKWI_NAME, BASICPAY, SUDANG, PAY
FROM EMPVIEW
WHERE EMP_ID=1066;
--WHERE EMP_NAME='김정용';
--WHERE BUSEO_NAME='개발부';
--WHERE JIKWI_NAME='과장';

--4.직원정보수정
UPDATE TBL_EMP
SET EMP_NAME='김정용', SSN='960608-2234567', IBSADATE=TO_DATE('2000-01-01', 'YYYY-MM-DD')
  , CITY_ID=(SELECT CITY_ID FROM TBL_CITY WHERE CITY_NAME='강원')
  , TEL='010-2731-3153'
  , BUSEO_ID=(SELECT BUSEO_ID FROM TBL_BUSEO WHERE BUSEO_NAME='개발부')
  , JIKWI_ID=(SELECT JIKWI_ID FROM TBL_JIKWI WHERE JIKWI_NAME='이사')
  , BASICPAY=6000000, SUDANG=1500000
WHERE EMP_ID=1066;

--5.직원정보삭제
DELETE TBL_EMP WHERE EMP_ID=1066;

ROLLBACK;
COMMIT;
SELECT * FROM EMPVIEW ORDER BY EMP_ID;



--------------------------------------------------------------------------------
--  WebApp12_1 (22.04.21) tbl_member, tbl_memberscore   
--------------------------------------------------------------------------------
SELECT * FROM TBL_MEMBER;
--ADD()
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '김정용', '010-0000-0000')
;
--LISTS()
SELECT SID, NAME, TEL FROM TBL_MEMBER ORDER BY SID
;
--COUNT()
SELECT COUNT(*) AS COUNT FROM TBL_MEMBER
;
--SEARCHMEMBER()
SELECT SID, NAME, TEL FROM TBL_MEMBER WHERE SID=9
;
--MODIFY()
UPDATE TBL_MEMBER SET NAME='김정용', TEL='010-0001-0001' WHERE SID=9
;
--REMOVE()
DELETE TBL_MEMBER WHERE SID=9
;
--REFCOUNT()
SELECT COUNT(*) AS COUNT FROM TBL_MEMBERSCORE WHERE SID=9
;

SELECT * FROM TBL_MEMBERSCORE;
SELECT * FROM TBL_MEMBER;
ROLLBACK;
COMMIT;





















